# Geodata products {#Ch05}

Some raw data need extensive processing before EGVs can be created, many EGVs 
depend on processing raw geodata into geodata products before EGVs can be create, 
and in some cases, EGV itself could be created from ras geodata, but it has 
to be spatially restricted to certain locations. This chapter describes these geodata 
products and procedures involved in creating them.

## Terrain products {#Ch05.01}

krā

## Soil texture product {#Ch05.02}

In this section one united layer describing categorised soil texture (sand=1, 
silt=2, clay=3, organic=4) is created from multiple preprocessed soil texture 
data sources. Creation of soil texture product consisted of multiple overlay steps. 
These steps are illustrated together with processed geodata used:

1. the basis soil texture source was [Soil texture from the European Soil Database](#Ch04.07.02), 
this layer had to be reclassified to match other layers as it was not performed 
during preprocessing;

2. the layer from the first step was overlaid by [Latvian Quarternary geology data](#Ch04.07.04) 
written as numeric starting with 1;

3. the layer from the second step was overlaid by [20th century topsoil in Latvian farmland](#Ch04.07.03) 
written as numeric starting with 1;

4. the layer from [Organic soils as modelled by Silava](#Ch04.07.05) (presence-only) 
was overlaid by [Organic soils as modelled by University of Latvia](#Ch04.07.06) 
(presence-absence). After the overlay, it was classified as presence-only;

5. the layer from the third step was overlaid by the layer from the fourth and 
saved for EGV creation.


```{r,eval=FALSE}
# libs ----
if(!require(terra)) {install.packages("terra"); require(terra)}

# step 1
step1=rast("./RasterGrids_10m/2024/SoilTXT_ESDAC.tif")
step1x=ifel(step1==1,1,
            ifel(step1==2,2,
                 ifel(step1==3,2,
                      ifel(step1==4,3,
                           ifel(step1==8,4,NA)))))
plot(step1x)
step1xy=as.numeric(step1x)
plot(step1xy)


# step 2
step2a=rast("./RasterGrids_10m/2024/SoilTXT_QuarternaryLV.tif")
step2a=as.numeric(step2a)+1
plot(step2a)

step2=cover(step2a,step1x)
plot(step2)

# step 3
step3a=rast("./RasterGrids_10m/2024/SoilTXT_topSoilLV.tif")
step3a=as.numeric(step3a)+1
plot(step3a)

step3=cover(step3a,step2)
plot(step3)

# step 4
step4a=rast("./RasterGrids_10m/2024/SoilTXT_OrganicLU.tif")
step4b=rast("./RasterGrids_10m/2024/SoilTXT_OrganicSilava.tif")

step4c=cover(step4a,step4b)

step4=ifel(step4c==1,4,NA)
plot(step4)

# step 5

step5=cover(step4,step3)
plot(step5)

writeRaster(step5,
           "./RasterGrids_10m/2024/SoilTXT_combined.tif",
           overwrite=TRUE)


```



## Landscape classification {#Ch05.03}

krā

## Landscape diversity {#Ch05.04}

krā

### Forest diversity {#Ch05.04.01}

krā

### Farmland diversity {#Ch05.04.02}

krā


### Landscape in general diversity {#Ch05.04.03}

krā
